apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-db
  name: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/src-default: "true"
        io.kompose.service: customer-db
    spec:
      containers:
        - env:
            - name: customer_host
              value: customer-db
            - name: customer_port
              value: "50080"
          image: gcr.io/distributedsystems-swsr1249/customer_db:latest
          name: customer-db
          resources: {}
      hostname: customer-db
      restartPolicy: Always
status: {}
