# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ustomer.proto\"\x1f\n\x0eGetDataRequest\x12\r\n\x05query\x18\x01 \x01(\t\"<\n\x0fGetDataResponse\x12\x12\n\x04rows\x18\x01 \x03(\x0b\x32\x04.Row\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Error\"\"\n\x11InsertDataRequest\x12\r\n\x05query\x18\x01 \x01(\t\">\n\x12InsertDataResponse\x12\x11\n\tinsert_id\x18\x01 \x01(\x03\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Error\"\"\n\x11UpdateDataRequest\x12\r\n\x05query\x18\x01 \x01(\t\"B\n\x12UpdateDataResponse\x12\x15\n\raffected_rows\x18\x01 \x01(\x03\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Error\"\"\n\x11\x44\x65leteDataRequest\x12\r\n\x05query\x18\x01 \x01(\t\"B\n\x12\x44\x65leteDataResponse\x12\x15\n\raffected_rows\x18\x01 \x01(\x03\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Error\"#\n\x03Row\x12\x1c\n\x06values\x18\x01 \x03(\x0b\x32\x0c.ColumnValue\"8\n\x0b\x43olumnValue\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63olumn_value\x18\x02 \x01(\t\"2\n\x05\x45rror\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xf3\x01\n\x16\x43ustomerDatabaseServer\x12.\n\x07GetData\x12\x0f.GetDataRequest\x1a\x10.GetDataResponse\"\x00\x12\x37\n\nInsertData\x12\x12.InsertDataRequest\x1a\x13.InsertDataResponse\"\x00\x12\x37\n\nUpdateData\x12\x12.UpdateDataRequest\x1a\x13.UpdateDataResponse\"\x00\x12\x37\n\nDeleteData\x12\x12.DeleteDataRequest\x1a\x13.DeleteDataResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETDATAREQUEST._serialized_start=18
  _GETDATAREQUEST._serialized_end=49
  _GETDATARESPONSE._serialized_start=51
  _GETDATARESPONSE._serialized_end=111
  _INSERTDATAREQUEST._serialized_start=113
  _INSERTDATAREQUEST._serialized_end=147
  _INSERTDATARESPONSE._serialized_start=149
  _INSERTDATARESPONSE._serialized_end=211
  _UPDATEDATAREQUEST._serialized_start=213
  _UPDATEDATAREQUEST._serialized_end=247
  _UPDATEDATARESPONSE._serialized_start=249
  _UPDATEDATARESPONSE._serialized_end=315
  _DELETEDATAREQUEST._serialized_start=317
  _DELETEDATAREQUEST._serialized_end=351
  _DELETEDATARESPONSE._serialized_start=353
  _DELETEDATARESPONSE._serialized_end=419
  _ROW._serialized_start=421
  _ROW._serialized_end=456
  _COLUMNVALUE._serialized_start=458
  _COLUMNVALUE._serialized_end=514
  _ERROR._serialized_start=516
  _ERROR._serialized_end=566
  _CUSTOMERDATABASESERVER._serialized_start=569
  _CUSTOMERDATABASESERVER._serialized_end=812
# @@protoc_insertion_point(module_scope)
