# coding: utf-8

"""
    Buyer Account API

    API for creating and managing buyer accounts  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from buyer_client.configuration import Configuration


class CardDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'card_number': 'int',
        'expiration_date': 'str',
        'buyer_id': 'int'
    }

    attribute_map = {
        'name': 'name',
        'card_number': 'card_number',
        'expiration_date': 'expiration_date',
        'buyer_id': 'buyer_id'
    }

    def __init__(self, name=None, card_number=None, expiration_date=None, buyer_id=None, _configuration=None):  # noqa: E501
        """CardDetails - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._card_number = None
        self._expiration_date = None
        self._buyer_id = None
        self.discriminator = None

        self.name = name
        if card_number is not None:
            self.card_number = card_number
        self.expiration_date = expiration_date
        self.buyer_id = buyer_id

    @property
    def name(self):
        """Gets the name of this CardDetails.  # noqa: E501


        :return: The name of this CardDetails.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CardDetails.


        :param name: The name of this CardDetails.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def card_number(self):
        """Gets the card_number of this CardDetails.  # noqa: E501


        :return: The card_number of this CardDetails.  # noqa: E501
        :rtype: int
        """
        return self._card_number

    @card_number.setter
    def card_number(self, card_number):
        """Sets the card_number of this CardDetails.


        :param card_number: The card_number of this CardDetails.  # noqa: E501
        :type: int
        """

        self._card_number = card_number

    @property
    def expiration_date(self):
        """Gets the expiration_date of this CardDetails.  # noqa: E501


        :return: The expiration_date of this CardDetails.  # noqa: E501
        :rtype: str
        """
        return self._expiration_date

    @expiration_date.setter
    def expiration_date(self, expiration_date):
        """Sets the expiration_date of this CardDetails.


        :param expiration_date: The expiration_date of this CardDetails.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and expiration_date is None:
            raise ValueError("Invalid value for `expiration_date`, must not be `None`")  # noqa: E501

        self._expiration_date = expiration_date

    @property
    def buyer_id(self):
        """Gets the buyer_id of this CardDetails.  # noqa: E501


        :return: The buyer_id of this CardDetails.  # noqa: E501
        :rtype: int
        """
        return self._buyer_id

    @buyer_id.setter
    def buyer_id(self, buyer_id):
        """Sets the buyer_id of this CardDetails.


        :param buyer_id: The buyer_id of this CardDetails.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and buyer_id is None:
            raise ValueError("Invalid value for `buyer_id`, must not be `None`")  # noqa: E501

        self._buyer_id = buyer_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CardDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CardDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CardDetails):
            return True

        return self.to_dict() != other.to_dict()
