# coding: utf-8

"""
    Buyer Account API

    API for creating and managing buyer accounts  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from buyer_client.configuration import Configuration


class InlineResponse2007Items(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item_id': 'str',
        'item_name': 'str',
        'item_category': 'str',
        'sale_price': 'float',
        'quantity': 'int'
    }

    attribute_map = {
        'item_id': 'item_id',
        'item_name': 'item_name',
        'item_category': 'item_category',
        'sale_price': 'sale_price',
        'quantity': 'quantity'
    }

    def __init__(self, item_id=None, item_name=None, item_category=None, sale_price=None, quantity=None, _configuration=None):  # noqa: E501
        """InlineResponse2007Items - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._item_id = None
        self._item_name = None
        self._item_category = None
        self._sale_price = None
        self._quantity = None
        self.discriminator = None

        if item_id is not None:
            self.item_id = item_id
        if item_name is not None:
            self.item_name = item_name
        if item_category is not None:
            self.item_category = item_category
        if sale_price is not None:
            self.sale_price = sale_price
        if quantity is not None:
            self.quantity = quantity

    @property
    def item_id(self):
        """Gets the item_id of this InlineResponse2007Items.  # noqa: E501


        :return: The item_id of this InlineResponse2007Items.  # noqa: E501
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id):
        """Sets the item_id of this InlineResponse2007Items.


        :param item_id: The item_id of this InlineResponse2007Items.  # noqa: E501
        :type: str
        """

        self._item_id = item_id

    @property
    def item_name(self):
        """Gets the item_name of this InlineResponse2007Items.  # noqa: E501


        :return: The item_name of this InlineResponse2007Items.  # noqa: E501
        :rtype: str
        """
        return self._item_name

    @item_name.setter
    def item_name(self, item_name):
        """Sets the item_name of this InlineResponse2007Items.


        :param item_name: The item_name of this InlineResponse2007Items.  # noqa: E501
        :type: str
        """

        self._item_name = item_name

    @property
    def item_category(self):
        """Gets the item_category of this InlineResponse2007Items.  # noqa: E501


        :return: The item_category of this InlineResponse2007Items.  # noqa: E501
        :rtype: str
        """
        return self._item_category

    @item_category.setter
    def item_category(self, item_category):
        """Sets the item_category of this InlineResponse2007Items.


        :param item_category: The item_category of this InlineResponse2007Items.  # noqa: E501
        :type: str
        """

        self._item_category = item_category

    @property
    def sale_price(self):
        """Gets the sale_price of this InlineResponse2007Items.  # noqa: E501


        :return: The sale_price of this InlineResponse2007Items.  # noqa: E501
        :rtype: float
        """
        return self._sale_price

    @sale_price.setter
    def sale_price(self, sale_price):
        """Sets the sale_price of this InlineResponse2007Items.


        :param sale_price: The sale_price of this InlineResponse2007Items.  # noqa: E501
        :type: float
        """

        self._sale_price = sale_price

    @property
    def quantity(self):
        """Gets the quantity of this InlineResponse2007Items.  # noqa: E501


        :return: The quantity of this InlineResponse2007Items.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this InlineResponse2007Items.


        :param quantity: The quantity of this InlineResponse2007Items.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2007Items, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2007Items):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2007Items):
            return True

        return self.to_dict() != other.to_dict()
