# coding: utf-8

"""
    Seller API

    API for managing seller accounts and items for sale  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seller_client
from seller_client.api.items_api import ItemsApi  # noqa: E501
from seller_client.rest import ApiException


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self):
        self.api = seller_client.api.items_api.ItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_display_get(self):
        """Test case for display_get

        Display items  # noqa: E501
        """
        pass

    def test_items_item_id_delete(self):
        """Test case for items_item_id_delete

        Remove an item from sale  # noqa: E501
        """
        pass

    def test_items_item_id_sale_price_put(self):
        """Test case for items_item_id_sale_price_put

        Change the sale price of an item  # noqa: E501
        """
        pass

    def test_items_post(self):
        """Test case for items_post

        Put an item for sale  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
