# coding: utf-8

"""
    Seller API

    API for managing seller accounts and items for sale  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seller_client
from seller_client.api.sellers_api import SellersApi  # noqa: E501
from seller_client.rest import ApiException


class TestSellersApi(unittest.TestCase):
    """SellersApi unit test stubs"""

    def setUp(self):
        self.api = seller_client.api.sellers_api.SellersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_seller_rating_get(self):
        """Test case for seller_rating_get

        Get seller rating  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
