# coding: utf-8

"""
    Seller API

    API for managing seller accounts and items for sale  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seller_client
from seller_client.api.authentication_api import AuthenticationApi  # noqa: E501
from seller_client.rest import ApiException


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = seller_client.api.authentication_api.AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login_post(self):
        """Test case for login_post

        Login  # noqa: E501
        """
        pass

    def test_logout_post(self):
        """Test case for logout_post

        Logout  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
