# coding: utf-8

"""
    Seller API

    API for managing seller accounts and items for sale  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seller_client
from seller_client.models.inline_response2006_items import InlineResponse2006Items  # noqa: E501
from seller_client.rest import ApiException


class TestInlineResponse2006Items(unittest.TestCase):
    """InlineResponse2006Items unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006Items(self):
        """Test InlineResponse2006Items"""
        # FIXME: construct object with mandatory attributes with example values
        # model = seller_client.models.inline_response2006_items.InlineResponse2006Items()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
