# coding: utf-8

"""
    Seller API

    API for managing seller accounts and items for sale  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import seller_client
from seller_client.models.inline_response500 import InlineResponse500  # noqa: E501
from seller_client.rest import ApiException


class TestInlineResponse500(unittest.TestCase):
    """InlineResponse500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse500(self):
        """Test InlineResponse500"""
        # FIXME: construct object with mandatory attributes with example values
        # model = seller_client.models.inline_response500.InlineResponse500()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
