# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2007Items(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, item_id: str=None, item_name: str=None, item_category: str=None, sale_price: float=None, quantity: int=None):  # noqa: E501
        """InlineResponse2007Items - a model defined in Swagger

        :param item_id: The item_id of this InlineResponse2007Items.  # noqa: E501
        :type item_id: str
        :param item_name: The item_name of this InlineResponse2007Items.  # noqa: E501
        :type item_name: str
        :param item_category: The item_category of this InlineResponse2007Items.  # noqa: E501
        :type item_category: str
        :param sale_price: The sale_price of this InlineResponse2007Items.  # noqa: E501
        :type sale_price: float
        :param quantity: The quantity of this InlineResponse2007Items.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'item_id': str,
            'item_name': str,
            'item_category': str,
            'sale_price': float,
            'quantity': int
        }

        self.attribute_map = {
            'item_id': 'item_id',
            'item_name': 'item_name',
            'item_category': 'item_category',
            'sale_price': 'sale_price',
            'quantity': 'quantity'
        }

        self._item_id = item_id
        self._item_name = item_name
        self._item_category = item_category
        self._sale_price = sale_price
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2007Items':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_7_items of this InlineResponse2007Items.  # noqa: E501
        :rtype: InlineResponse2007Items
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_id(self) -> str:
        """Gets the item_id of this InlineResponse2007Items.


        :return: The item_id of this InlineResponse2007Items.
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id: str):
        """Sets the item_id of this InlineResponse2007Items.


        :param item_id: The item_id of this InlineResponse2007Items.
        :type item_id: str
        """

        self._item_id = item_id

    @property
    def item_name(self) -> str:
        """Gets the item_name of this InlineResponse2007Items.


        :return: The item_name of this InlineResponse2007Items.
        :rtype: str
        """
        return self._item_name

    @item_name.setter
    def item_name(self, item_name: str):
        """Sets the item_name of this InlineResponse2007Items.


        :param item_name: The item_name of this InlineResponse2007Items.
        :type item_name: str
        """

        self._item_name = item_name

    @property
    def item_category(self) -> str:
        """Gets the item_category of this InlineResponse2007Items.


        :return: The item_category of this InlineResponse2007Items.
        :rtype: str
        """
        return self._item_category

    @item_category.setter
    def item_category(self, item_category: str):
        """Sets the item_category of this InlineResponse2007Items.


        :param item_category: The item_category of this InlineResponse2007Items.
        :type item_category: str
        """

        self._item_category = item_category

    @property
    def sale_price(self) -> float:
        """Gets the sale_price of this InlineResponse2007Items.


        :return: The sale_price of this InlineResponse2007Items.
        :rtype: float
        """
        return self._sale_price

    @sale_price.setter
    def sale_price(self, sale_price: float):
        """Sets the sale_price of this InlineResponse2007Items.


        :param sale_price: The sale_price of this InlineResponse2007Items.
        :type sale_price: float
        """

        self._sale_price = sale_price

    @property
    def quantity(self) -> int:
        """Gets the quantity of this InlineResponse2007Items.


        :return: The quantity of this InlineResponse2007Items.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this InlineResponse2007Items.


        :param quantity: The quantity of this InlineResponse2007Items.
        :type quantity: int
        """

        self._quantity = quantity
