# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2007_items import InlineResponse2007Items
from swagger_server import util


class InlineResponse2007(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, items: List[InlineResponse2007Items]=None):  # noqa: E501
        """InlineResponse2007 - a model defined in Swagger

        :param items: The items of this InlineResponse2007.  # noqa: E501
        :type items: List[InlineResponse2007Items]
        """
        self.swagger_types = {
            'items': List[InlineResponse2007Items]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2007':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_7 of this InlineResponse2007.  # noqa: E501
        :rtype: InlineResponse2007
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[InlineResponse2007Items]:
        """Gets the items of this InlineResponse2007.


        :return: The items of this InlineResponse2007.
        :rtype: List[InlineResponse2007Items]
        """
        return self._items

    @items.setter
    def items(self, items: List[InlineResponse2007Items]):
        """Sets the items of this InlineResponse2007.


        :param items: The items of this InlineResponse2007.
        :type items: List[InlineResponse2007Items]
        """

        self._items = items
