# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\"\x1b\n\nGetRequest\x12\r\n\x05query\x18\x01 \x01(\t\"9\n\x0bGetResponse\x12\x13\n\x04rows\x18\x01 \x03(\x0b\x32\x05.Rows\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Issue\"\x1e\n\rInsertRequest\x12\r\n\x05query\x18\x01 \x01(\t\":\n\x0eInsertResponse\x12\x11\n\tinsert_id\x18\x01 \x01(\x03\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Issue\"\x1e\n\rUpdateRequest\x12\r\n\x05query\x18\x01 \x01(\t\">\n\x0eUpdateResponse\x12\x15\n\raffected_rows\x18\x01 \x01(\x03\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Issue\"\x1e\n\rDeleteRequest\x12\r\n\x05query\x18\x01 \x01(\t\">\n\x0e\x44\x65leteResponse\x12\x15\n\raffected_rows\x18\x01 \x01(\x03\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Issue\"!\n\x04Rows\x12\x19\n\x06values\x18\x01 \x03(\x0b\x32\t.ColValue\"5\n\x08\x43olValue\x12\x13\n\x0b\x63olumn_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63olumn_value\x18\x02 \x01(\t\"2\n\x05Issue\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xc2\x01\n\x15ProductDatabaseServer\x12\"\n\x03Get\x12\x0b.GetRequest\x1a\x0c.GetResponse\"\x00\x12+\n\x06Insert\x12\x0e.InsertRequest\x1a\x0f.InsertResponse\"\x00\x12+\n\x06Update\x12\x0e.UpdateRequest\x1a\x0f.UpdateResponse\"\x00\x12+\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETREQUEST._serialized_start=17
  _GETREQUEST._serialized_end=44
  _GETRESPONSE._serialized_start=46
  _GETRESPONSE._serialized_end=103
  _INSERTREQUEST._serialized_start=105
  _INSERTREQUEST._serialized_end=135
  _INSERTRESPONSE._serialized_start=137
  _INSERTRESPONSE._serialized_end=195
  _UPDATEREQUEST._serialized_start=197
  _UPDATEREQUEST._serialized_end=227
  _UPDATERESPONSE._serialized_start=229
  _UPDATERESPONSE._serialized_end=291
  _DELETEREQUEST._serialized_start=293
  _DELETEREQUEST._serialized_end=323
  _DELETERESPONSE._serialized_start=325
  _DELETERESPONSE._serialized_end=387
  _ROWS._serialized_start=389
  _ROWS._serialized_end=422
  _COLVALUE._serialized_start=424
  _COLVALUE._serialized_end=477
  _ISSUE._serialized_start=479
  _ISSUE._serialized_end=529
  _PRODUCTDATABASESERVER._serialized_start=532
  _PRODUCTDATABASESERVER._serialized_end=726
# @@protoc_insertion_point(module_scope)
