# coding: utf-8

"""
    Buyer Account API

    API for creating and managing buyer accounts  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import buyer_client
from buyer_client.models.card_details import CardDetails  # noqa: E501
from buyer_client.rest import ApiException


class TestCardDetails(unittest.TestCase):
    """CardDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCardDetails(self):
        """Test CardDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = buyer_client.models.card_details.CardDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
