# coding: utf-8

"""
    Buyer Account API

    API for creating and managing buyer accounts  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import buyer_client
from buyer_client.api.buyer_account_api import BuyerAccountApi  # noqa: E501
from buyer_client.rest import ApiException


class TestBuyerAccountApi(unittest.TestCase):
    """BuyerAccountApi unit test stubs"""

    def setUp(self):
        self.api = buyer_client.api.buyer_account_api.BuyerAccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_account_post(self):
        """Test case for account_post

        Create a new buyer account  # noqa: E501
        """
        pass

    def test_login_post(self):
        """Test case for login_post

        Log in to an existing account  # noqa: E501
        """
        pass

    def test_logout_buyer_id_get(self):
        """Test case for logout_buyer_id_get

        Log out of an existing account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
