# coding: utf-8

"""
    Buyer Account API

    API for creating and managing buyer accounts  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import buyer_client
from buyer_client.api.cart_api import CartApi  # noqa: E501
from buyer_client.rest import ApiException


class TestCartApi(unittest.TestCase):
    """CartApi unit test stubs"""

    def setUp(self):
        self.api = buyer_client.api.cart_api.CartApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cart_add_post(self):
        """Test case for cart_add_post

        Add item to shopping cart  # noqa: E501
        """
        pass

    def test_cart_remove_delete(self):
        """Test case for cart_remove_delete

        Remove item from shopping cart  # noqa: E501
        """
        pass

    def test_clear_cart_post(self):
        """Test case for clear_cart_post

        Clear the shopping cart for a given buyer  # noqa: E501
        """
        pass

    def test_display_cart_get(self):
        """Test case for display_cart_get

        Get the contents of the shopping cart for a given buyer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
