# coding: utf-8

"""
    Buyer Account API

    API for creating and managing buyer accounts  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import buyer_client
from buyer_client.api.buyer_actions_api import BuyerActionsApi  # noqa: E501
from buyer_client.rest import ApiException


class TestBuyerActionsApi(unittest.TestCase):
    """BuyerActionsApi unit test stubs"""

    def setUp(self):
        self.api = buyer_client.api.buyer_actions_api.BuyerActionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_purchase_history_get(self):
        """Test case for purchase_history_get

        Get purchase history  # noqa: E501
        """
        pass

    def test_purchase_post(self):
        """Test case for purchase_post

        Purchase items added in the cart  # noqa: E501
        """
        pass

    def test_search_items_get(self):
        """Test case for search_items_get

        Search for items  # noqa: E501
        """
        pass

    def test_seller_feedback_post(self):
        """Test case for seller_feedback_post

        Provide seller Feedback  # noqa: E501
        """
        pass

    def test_seller_rating_get(self):
        """Test case for seller_rating_get

        Get seller rating  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
