# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from seller_server.models.base_model_ import Model
from seller_server.models.inline_response2006_items import InlineResponse2006Items
from seller_server import util


class InlineResponse2006(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, items: List[InlineResponse2006Items]=None):  # noqa: E501
        """InlineResponse2006 - a model defined in Swagger

        :param items: The items of this InlineResponse2006.  # noqa: E501
        :type items: List[InlineResponse2006Items]
        """
        self.swagger_types = {
            'items': List[InlineResponse2006Items]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2006':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_6 of this InlineResponse2006.  # noqa: E501
        :rtype: InlineResponse2006
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[InlineResponse2006Items]:
        """Gets the items of this InlineResponse2006.


        :return: The items of this InlineResponse2006.
        :rtype: List[InlineResponse2006Items]
        """
        return self._items

    @items.setter
    def items(self, items: List[InlineResponse2006Items]):
        """Sets the items of this InlineResponse2006.


        :param items: The items of this InlineResponse2006.
        :type items: List[InlineResponse2006Items]
        """

        self._items = items
